title: Security and Privacy Conference Deadlines
description: Countdowns to top Security and Privacy conference deadlines.
author: Bogdan Kulynych

domain: "i1-deadlines.github.io"
baseurl: "/i1-deadlines2.github.io"

twitter_username: hiddenmarkov
github_repo: i1-deadlines.github.io

markdown: kramdown
