title: Security and Privacy Conference Deadlines
description: Countdowns to top Security and Privacy conference deadlines.
author: Bogdan Kulynych

domain: "sec-deadlines.github.io"
baseurl: ""

twitter_username: hiddenmarkov
github_username: sec-deadlines
github_repo: sec-deadlines
ga_id: UA-104921371-1

markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
