title: Security and Privacy Conference Deadlines
description: Countdowns to top Security and Privacy conference deadlines.
author: Bogdan Kulynych

domain: "i1-deadlines.github.io"
baseurl: "/i1-deadlines2.github.ui"

github_username: Dbof
github_repo: i1-deadlines.github.io
twitter_username: TheDbof

markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
